# Generated by Django 2.1.5 on 2019-02-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('added', models.DateTimeField(verbose_name='date published')),
                ('url', models.URLField(db_index=True, max_length=128, unique=True)),
                ('email', models.EmailField(blank=True, max_length=70, unique=True)),
            ],
        ),
    ]
