# Generated by Django 2.1.5 on 2019-02-10 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenuePricing',
            fields=[
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='venues.Venues')),
                ('price', models.IntegerField(blank=True)),
                ('tables', models.BooleanField(default=False)),
                ('cutlery', models.BooleanField(default=False)),
                ('crockery', models.BooleanField(default=False)),
                ('accomodation', models.BooleanField(default=False)),
            ],
        ),
    ]
