# Generated by Django 2.1.5 on 2019-02-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_venuepricing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venuepricing',
            name='name',
        ),
        migrations.AddField(
            model_name='venues',
            name='accomodation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venues',
            name='crockery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venues',
            name='cutlery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venues',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venues',
            name='tables',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='VenuePricing',
        ),
    ]
