# Generated by Django 2.1.5 on 2019-02-10 12:03

from django.db import migrations, models
import venues.models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0003_auto_20190210_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='venues',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=venues.models.get_image_path),
        ),
    ]
