# Generated by Django 2.1.5 on 2019-02-10 12:23

from django.db import migrations, models
import venues.models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0004_venues_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venues',
            name='profile_image',
            field=models.ImageField(blank=True, default='media/default.jpg', null=True, upload_to=venues.models.get_image_path),
        ),
    ]
